# Generated by Django 4.2.1 on 2023-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('realise_date', models.DateField()),
                ('image', models.BinaryField()),
            ],
        ),
    ]
