# Generated by Django 4.2.1 on 2023-05-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fk', to='gameapp.category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_fk', to='gameapp.game')),
            ],
        ),
    ]
